# outlier-detection

In [1]:
import pandas as pd
import sys
print(sys.version)

3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]

In [2]:
from pycaret.anomaly import *
df = pd.read_csv('../../Dataset/iris-full.csv')

exp_name = setup(data = df)
abod = create_model('abod')
plot_model(abod, plot = 'tsne')

ModuleNotFoundError: No module named 'pycaret'

## Implementasi Model ke dataset

In [28]:
# Assign model -> hasilkan dataframe dengan kolom anomaly
df_anomaly = assign_model(abod)

## Menampilkan Data dengan skor outlier tertinggi

In [29]:
df_sorted = df_anomaly.sort_values(by="Anomaly_Score", ascending=False).reset_index(drop=True)
df_sorted.head()

,id,Class,sepal length,sepal width,petal length,petal width,Anomaly,Anomaly_Score
0,107,Iris-virginica,4.9,2.5,4.5,1.7,1,-0.001276
1,123,Iris-virginica,7.7,2.8,6.7,2.0,1,-0.004978
2,119,Iris-virginica,7.7,2.6,6.9,2.3,1,-0.005204
3,118,Iris-virginica,7.7,3.8,6.7,2.2,1,-0.005361
4,120,Iris-virginica,6.0,2.2,5.0,1.5,1,-0.006080

## Menghapus Data dengan 2 skor outlier tertinggi

In [30]:
df_removed = df_sorted.iloc[2:].reset_index(drop=True)
dataset = df_removed.sort_values(by="id").reset_index(drop=True)
dataset.head()

,id,Class,sepal length,sepal width,petal length,petal width,Anomaly,Anomaly_Score
0,1,Iris-setosa,5.1,3.5,1.4,0.2,0,-0.010918
1,2,Iris-setosa,4.9,3.0,1.4,0.2,0,-0.105879
2,3,Iris-setosa,4.7,3.2,1.3,0.2,0,-0.160850
3,4,Iris-setosa,4.6,3.1,1.5,0.2,0,-0.108965
4,5,Iris-setosa,5.0,3.6,1.4,0.2,0,-0.103372

In [31]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             148 non-null    int32
 1   Class          148 non-null    category
 2   sepal length   148 non-null    float32
 3   sepal width    148 non-null    float32
 4   petal length   148 non-null    float32
 5   petal width    148 non-null    float32
 6   Anomaly        148 non-null    int32
 7   Anomaly_Score  148 non-null    float64
dtypes: category(1), float32(4), float64(1), int32(2)
memory usage: 5.0 KB